name: Get badminton reservation updates every 5 minutes

on:
  schedule:
    - cron: "3-59/5 * * * *"   # 每 5 分钟运行一次
  workflow_dispatch:          # 也可以手动触发

permissions:
  contents: write

jobs:
  run-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install tzdata

      - name: Run main-git.py
        env:
          GMAIL_PWD: ${{ secrets.GMAIL_PWD }}
        run: python badminton/main-git.py

      - name: Commit updated state/log if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add badminton/last_result.txt badminton/script.log
          git diff --cached --quiet || git commit -m "chore: update last_result & log [skip ci]"
          git push
